Citation Plugin version 1.0.0
mozillascience/citation-plugin pull request #2
Opened 2017-02-14 22:14 UTC by sam1360

2017-02-15 05:53 UTC, nokeeo requested changes

2017-02-15 05:53 UTC, nokeeo commented on Plugin/citation-plugin.html
> +<!DOCTYPE html>
Remove dead code in the entire file.

2017-02-15 05:53 UTC, nokeeo commented on Plugin/package.json
> +  "version": "0.0.1",
Change version to 1.0.0

2017-02-15 05:53 UTC, nokeeo commented on Plugin/.eslintignore
> +**/*.conf
New line to end file

2017-02-15 05:53 UTC, nokeeo commented on Plugin/citation-plugin.js
> +
Please add JSdoc comments to all functions.

2017-02-15 05:53 UTC, nokeeo commented on Plugin/style.css
> +    box-shadow: 0 0 0 0 rgba(97, 181, 255, 0);
rgba not using alpha.  Use hex instead

2017-02-15 05:53 UTC, nokeeo commented on Plugin/.eslintrc.json
> +}
No new line

2017-02-15 05:53 UTC, nokeeo commented on Plugin/.eslintrc.json
> +        "no-unused-vars": ["error", { "args": "none" }]
Just a note we added a rule in [this](https://github.com/mozillascience/CitationCore/pull/6) PR.  Not merged, but we might want to add that rule here.

2017-02-15 05:53 UTC, nokeeo commented on Plugin/package.json
> +  "author": "Samuel Mosher",
Please add authors of the project and their emails. Should also include the mozilla user. An example can be found [here](https://github.com/mozillascience/CitationCore/blob/master/package.json).

2017-02-15 05:53 UTC, nokeeo commented on README.md
> +cp dev/pre-commit .git/hooks/
Please include this hook script in the PR.

2017-02-15 05:53 UTC, nokeeo commented on Plugin/.eslintignore
> +**/*.html
Just curious, why are we ignoring files that match these patterns

2017-02-16 21:25 UTC, faokryn requested changes

2017-02-16 21:25 UTC, faokryn commented on Plugin/citation-plugin.html
> +                    <td><input type="text" style="width:100%;" id="citation-URL"></td>
Why are you using the style class instead of a class?
(Also below)

2017-02-16 21:25 UTC, faokryn commented on Plugin/manifest.json
> +    "description": "A demo for the Software Citation Tools Plugin",
What is the purpose of manifest.json? Should this be referred to as a demo?

2017-02-16 21:25 UTC, faokryn commented on Plugin/style.css
> +    background-color: #fff;
Keep the color style consistent. Use #ffffff

2017-02-16 21:25 UTC, faokryn commented on README.md
> +Once the install script finishes, navigate to [about:debugging#addons](about:debugging#addons). Once there, select the the "Load Temporary Add-on", navigate to the Plugin directory and select the man
In 'select the the "Load Temporary Add-On"', "the" is repeated twice. However, it isn't followed up by "button" or "link" or the like, and the article should probably be removed all together, changing it to 'select "Load Temporary Add-On"'

2017-02-16 21:25 UTC, faokryn commented on dev/pre-commit
> +fi
Add EOF new line.

2017-02-16 21:25 UTC, faokryn commented on Plugin/.eslintignore
> +**/*.conf
Add EOF new line.

2017-02-21 19:15 UTC, faokryn commented on README.md
> +Once the install script finishes, navigate to [about:debugging#addons](about:debugging#addons). Once there, select the the "Load Temporary Add-on", navigate to the Plugin directory and select the man
Any update on this requested change?

2017-02-21 19:15 UTC, faokryn commented on dev/pre-commit
> +fi
Any update on this requested change?

2017-02-21 20:27 UTC, faokryn approved these changes

2017-02-21 20:27 UTC, faokryn commented
👍 lgtm assuming Eric's satisfied with the JSdoc comments and hook script

2017-02-21 22:18 UTC, nokeeo approved these changes

2017-02-21 22:20 UTC, merged